config/routes.rb
Bankpublic::Application.routes.draw do
  resources :banc_wheres

  get 'bancfinder/find'

  root :to => "home#index"

  #Routes de base du site internet
  get '/home/contact' => "home#contact"
  get '/home/informations' => "home#informations"


  #Routes pour le finder
  get '/home/bancfinder' => "bancfinder#find"

  #Routes pour l'authentification utilisateur
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/banc_location.rb
# == Schema Information
#
# Table name: banc_locations
#
#  id          :integer          not null, primary key
#  n_rue       :integer
#  adress      :text
#  code_postal :integer
#  ville       :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class BancLocation < ActiveRecord::Base
end

app/models/banc_where.rb
# == Schema Information
#
# Table name: banc_wheres
#
#  id          :integer          not null, primary key
#  n_rue       :integer
#  adress      :text
#  code_postal :integer
#  ville       :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class BancWhere < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banc_wheres_controller.rb
class BancWheresController < ApplicationController
  before_action :set_banc_where, only: [:show, :edit, :update, :destroy]

  # GET /banc_wheres
  # GET /banc_wheres.json
  def index
    @banc_wheres = BancWhere.all
  end

  # GET /banc_wheres/1
  # GET /banc_wheres/1.json
  def show
  end

  # GET /banc_wheres/new
  def new
    @banc_where = BancWhere.new
  end

  # GET /banc_wheres/1/edit
  def edit
  end

  # POST /banc_wheres
  # POST /banc_wheres.json
  def create
    @banc_where = BancWhere.new(banc_where_params)

    respond_to do |format|
      if @banc_where.save
        format.html { redirect_to @banc_where, notice: 'Banc where was successfully created.' }
        format.json { render action: 'show', status: :created, location: @banc_where }
      else
        format.html { render action: 'new' }
        format.json { render json: @banc_where.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banc_wheres/1
  # PATCH/PUT /banc_wheres/1.json
  def update
    respond_to do |format|
      if @banc_where.update(banc_where_params)
        format.html { redirect_to @banc_where, notice: 'Banc where was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @banc_where }
      else
        format.html { render action: 'edit' }
        format.json { render json: @banc_where.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banc_wheres/1
  # DELETE /banc_wheres/1.json
  def destroy
    @banc_where.destroy
    respond_to do |format|
      format.html { redirect_to banc_wheres_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banc_where
      @banc_where = BancWhere.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banc_where_params
      params.require(:banc_where).permit(:n_rue, :adress, :code_postal, :ville)
    end
end

app/controllers/bancfinder_controller.rb
class BancfinderController < ApplicationController
  def find
  	@bounds = [[48.86473789999999 , 2.3898164],[48.864 , 2.38]]

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def contact
    end

    def informations
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/banc_wheres_helper.rb
module BancWheresHelper
end

app/helpers/bancfinder_helper.rb
module BancfinderHelper
end

app/views/banc_wheres/_form.html.erb
<%= simple_form_for(@banc_where) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :n_rue %>
    <%= f.input :adress %>
    <%= f.input :code_postal %>
    <%= f.input :ville %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/banc_wheres/edit.html.erb
<h1>Editing banc_where</h1>

<%= render 'form' %>

<%= link_to 'Show', @banc_where %> |
<%= link_to 'Back', banc_wheres_path %>

app/views/banc_wheres/index.html.erb
<h1>Listing banc_wheres</h1>

<table>
  <thead>
    <tr>
      <th>N rue</th>
      <th>Adress</th>
      <th>Code postal</th>
      <th>Ville</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banc_wheres.each do |banc_where| %>
      <tr>
        <td><%= banc_where.n_rue %></td>
        <td><%= banc_where.adress %></td>
        <td><%= banc_where.code_postal %></td>
        <td><%= banc_where.ville %></td>
        <td><%= link_to 'Show', banc_where %></td>
        <td><%= link_to 'Edit', edit_banc_where_path(banc_where) %></td>
        <td><%= link_to 'Destroy', banc_where, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Banc where', new_banc_where_path %>

app/views/banc_wheres/new.html.erb
<h1>New banc_where</h1>

<%= render 'form' %>

<%= link_to 'Back', banc_wheres_path %>

app/views/banc_wheres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>N rue:</strong>
  <%= @banc_where.n_rue %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @banc_where.adress %>
</p>

<p>
  <strong>Code postal:</strong>
  <%= @banc_where.code_postal %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @banc_where.ville %>
</p>

<%= link_to 'Edit', edit_banc_where_path(@banc_where) %> |
<%= link_to 'Back', banc_wheres_path %>

app/views/bancfinder/_carte_banc_public.html.erb
<div id="map">
	<script>
		var map = L.map('map')
		var bounds = <%= @bounds %>
		padded = L.latLngBounds( bounds ).pad(0.042)

		map.fitBounds(padded)

		marker = L.marker(bounds[1]).addTo(map)

		L.tileLayer('http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {
    				attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> ',
   			 		maxZoom: 18
			}).addTo(map);

	</script>



</div>

app/views/bancfinder/find.html.erb
<h1>Recherche d'un banc </h1>
<p>Vous recherchez un banc ? Vous voici a la bonne place</p>

<%= render "carte_banc_public" %>

app/views/home/_contenu_home.html.erb
<div class="small-block-grid-3"> 
    <li><%= image_tag("banc_public00.jpg", class:"th") %></li>
    <li><%= image_tag("banc_public01.jpg", class:"th") %></li> 
    <li><%= image_tag("banc_public02.jpg", class:"th") %></li> 
</ul>

app/views/home/_presentation.html.erb
<div  class="row">



    
    <div class="small-2 large-4 columns">
    
    </div>



    <div class="small-4 large-4 columns">
        <h1>Bienvenue sur <br>Bank public</h1>
            <p>Nous sommes un site sur lequel vous pourrez inclure les commentaires sur votre banc et trouvez les bancs à votre proximité</p>
    </div>



    <div class="small-6 large-4 columns">
        <%= image_tag("banc_public03.jpg", class:"th") %>
    </div>




</div>

app/views/home/contact.html.erb
<% render partial:"layouts/navigation_links" %>

<h1>Photos des membres du projet et les contact ainsi que les informations legales</h1>

app/views/home/index.html.erb
<%= render partial:"presentation" %>
<%= render partial:"contenu_home" %>

app/views/home/informations.html.erb
<% render partial:"layouts/navigation_links" %>

<h1>Dernieres actualité du site banc public</h1>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><%= link_to 'Logo_BankPublic', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

  <li><%= link_to 'Map', bancfinder_find_path %></li>

  <li><%= link_to 'Informations', home_informations_path %></li>

  <li><%= link_to 'Contact', home_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bankpublic" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bankpublic" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
     <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />


  <script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>



  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<%= link_to 'Edit account', edit_user_path %>